### ISSUE TITLE
Grey borders on transparent images after resize.

### ISSUE THREAD

**Issue by prototype23** [nodeca/pica#60] opened 2016-07-21 15:28 UTC
Hi, Can we avoid the grey outlines that appear on the edges of the image content when re-sizing transparent images?

Source:
http://i.share.pho.to/5c98cbcc_o.png

Result:
http://i.share.pho.to/55d46162_o.png

Settings used for the above example
http://i.share.pho.to/7bac2d68_o.jpeg

Since this happen when alphas are used, an option to change the black color that is filled when alphas are not used would be nice!

**Comment by puzrin** [comment] 2016-07-27 04:40
Hm... i thought we resolved alpha issues many time ago, but this is something new, and it's not regression (behave the same way in 1.x).

Can't promise any deadlines now, sorry.

**Comment by puzrin** [comment] 2016-07-31 13:11
Memo:

- http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=17926&start=45 interesting talk
- http://www.imagemagick.org/Usage/bugs/resize_halo/ the same bug in old ImageMagick described (and fixed)

**Comment by zhengsk** [comment] 2018-04-13 06:16
I have this problem too, hopely it can be fixed. 😘

**Comment by 2Owy** [comment] 2018-04-25 10:15
Sorry @puzrin I didn't find it.
Thx.

**Comment by jerrydeng** [comment] 2018-12-13 17:18
Any timeline for the resolution of this bug?

**Comment by puzrin** [comment] 2018-12-13 18:00
No plans, sorry.

**Comment by JuanSeBestia** [comment] 2018-12-13 19:50
Very sad :(

**Comment by jerrydeng** [comment] 2018-12-14 15:32
It seems to be a very subtle rounding bug in the nature of resizing and resampling algorithm.  I ran into similar issue trying to use hermite resizing algorithm directly. [hermite-resize-bug](https://stackoverflow.com/questions/32569867/scaling-down-image-with-hermite-resize-creates-thin-black-line-out-of-nowhere)

**Comment by puzrin** [comment] 2018-12-14 16:39
@jerrydeng see first posts again. This bug is caused by improper processing of edge conditions in alpha channel. If you know something else, not related - just create a reproducible sample and create one more issue.

**Comment by MRSalomao** [comment] 2019-06-21 17:10
Hi @puzrin, @a-rodin, @llacroix ! Thanks for your effort creating this awesome library :)

The issue described in this thread can be solved by premultiplying alpha before resizing, then "unpremultiplying" alpha when about to display the image to the user.

This comes at cost of some loss of color precision, but it does remove the undesired grayish outlines.

For other users reading this comment, you can easily implement these operations by adapting this short block of code: https://stackoverflow.com/a/13201044/2455153

Best!

**Comment by puzrin** [comment] 2019-06-21 20:19
@MRSalomao could you comment why people say premultiplication is used automatically https://stackoverflow.com/questions/23497925/how-can-i-stop-the-alpha-premultiplication-with-canvas-imagedata?

I remember #13 & just checked in spec - alpha is not premultiplied. But question on SO says it is. Why? Or do i miss something?

**Comment by MRSalomao** [comment] 2019-06-21 20:58
@puzrin , I did a quick test here:

![image](https://user-images.githubusercontent.com/4553084/59950572-f53e6880-943b-11e9-9a88-a15624d1f34e.png)

Seems that the source of confusion here comes from the difference between setting pixel values using `createImageData` versus reading from a preexisting image data (even if it's the pristine image data created by default when the canvas element is initialized) with `getImageData` then writing back to it with `putImageData`.

I'm still thinking about it, though. The alpha premultiplication step does not make Pica yield results identical to a Lanczos downscale using ImageMagick. They are similar, and certainly good enough for some use cases, but resizing with the exact same scaling factor with ImageMagick yields better results. I wonder if this is because ImageMagick takes a different approach where the lanczos kernel adapts to transparent pixels, damping their values, then normalizing the kernel before applying it.

**Comment by puzrin** [comment] 2019-06-21 21:10
I still don't understand. getImageData() and putImageData are the only way to access pixels fast. Where exactly distortion happens in get or in put?

Also note, ImageMagick uses pre-blur, and pica uses post-sharp. They are different by design and may have different sharpening defaults.

**Comment by MRSalomao** [comment] 2019-06-21 21:51
Ah, please disregard my last comment - it has nothing to do with using `createImageData` or not, as proved by this additional test:

![image](https://user-images.githubusercontent.com/4553084/59952797-19517800-9443-11e9-82b4-7844e91e7ee0.png)

Probably, this is what happens:

The distortion is introduced when `putImageData` is called, as alpha premultiplication probably happens inside that function call. Then, when imageData is read back, `getImageData` divides R/G/B by alpha before returning those values for each pixel, introducing even more rounding errors. 

>Also note, ImageMagick uses pre-blur, and pica uses post-sharp. They are different by design and may have different sharpening defaults.

Hmm! Thanks for the info! Let me see if I can get closer results by performing a pre-blur instead!

**Comment by chebum** [comment] 2021-11-19 19:10
I made a fix for the problem: 
https://github.com/chebum/pica/commit/ee5fc367fb1d2d500bff15c49c7260eb56731dc4

It implements the change suggested by @MRSalomao

Updated pica.js can be found here:
https://github.com/chebum/pica/tree/master/dist

**Comment by puzrin** [comment] 2021-11-23 16:03
@chebum thank you very much for example. Now i understand principle.

I have implementation-specific notes:

1. Branching (`if`) in inner `for` can reduce performance significantly. Probably, worth to make separate convolver for with/without alpha.
   - probably table[256] with reversed 16bit values instead of `mul(alpha) + div(256)` will work better.
2. While alpha range is `[0..255]`, scaling factor should be `[0..256]` to cover full range. Though that's not critical if symmetric reverse transform applied. See also note about table[256] above. It can provide proper scale (without need of special case for alpha = 255)  
3. It may be better to round result of premultiply/unpremultiply instead of drop fractional part.

**Comment by chebum** [comment] 2021-11-24 11:08
@puzrin 
Thank you for reviewing the commit. I tried the changes you suggested. Here is what I found:

> 1. Branching (`if`) in inner `for` can reduce performance significantly. Probably, worth to make separate convolver for with/without alpha.

I tried removing inner `ifs` by always using the most generic algorithm in convolver.js. It increased test suite pass time from 2s to 3s on my machine (I did several runs - the time is stable between runs). It seems that with test data, inner `ifs` save more time by avoiding additional multiplications, than they lose by disabling CPU optimizations. I didn't try that for WASM though.

>    * probably table[256] with reversed 16bit values instead of `mul(alpha) + div(256)` will work better.

It seems that division by 255 works faster than getting element from array by index in current version of Chromium. Here is a simple test I tried.

	const time = f => {
		let start = Date.now();
		f();
		console.log('Needed ', Date.now() - start, ' ms');
	};
	time(() => {
		let m = 0;
		for (let i = 0; i < 1000000; i++) {
			for (let j = 0; j < 255; j++) {
				m = j / 255;
			}
		}
	});
	time(() => {
		let m = 0;
		let alphas = [];
		for (let i = 0; i < 256; i++) {
		  alphas[i] = i / 255;
		}
		for (let i = 0; i < 1000000; i++) {
		 for (let j = 0; j < 255; j++) {
		   m = alphas[j];
		 }
		}
	});

The first test takes 90 ms, while the second one takes 135 ms on my laptop. Replacing divisions with array didn't improve test fixture time on my machine.

> 2. While alpha range is `[0..255]`, scaling factor should be `[0..256]` to cover full range. 

I'm not sure that's correct. Alpha of value 255 (fully opaque) shouldn't change weights of R, G and B components. Hence I divided by 255, not 256.

> 3. It may be better to round result of premultiply/unpremultiply instead of drop fractional part.

Could you clarify that in greater detail, please? I'm not sure I understood properly.

**Comment by puzrin** [comment] 2021-11-24 11:27
> It seems that division by 255 works faster than getting element from array by index in current version of Chromium. Here is a simple test I tried.

All such kinds of tests don't reflect what really happens in jit. Too long to explain. https://mrale.ph/ - dig it for begining.

The most obvious problem - in JS with `/255` you fall into floating point. That should not happen.

I'd recommend to use existing benchmark before/after patch, to make sure perf not reduced significantly.

> Could you clarify that in greater detail, please? I'm not sure I understood properly.

- For integers, (WASM), `2 / 3 = 0` without rounding, and 1 if rounded properly.
- Even if you send rounding to hell, your WASM result will diverge from JS, and that's not nice.

---

Sorry, i'm in another projects, and not ready to fall into technical discussion too deep. But you did the most important thing - showed the right principle of alpha rescale (need of missed premultiply/unpremultiply). That's enough for me to rewrite code when have some time.

**Comment by puzrin** [comment] 2021-11-24 15:45
> It seems that floating points do not make the results worse?

At first glance, perf things are not so bad. But, i guess, benchmark used WASM version https://github.com/nodeca/pica/blob/master/benchmark/benchmark.js#L9 - not disabled wasm.

Anyway, i'd prefer to do everything accurate at once, that will be faster than explain all edge cases. Please, don't consider my words as criticism, that's just some lack of time. I'm very thankful for your efforts, that will help to solve all issues about right resize of images with alpha channel.

Will try to create fixes in 1 month, and you will not need to maintain fork. If you know any other issues to solve - let me know.

**Comment by puzrin** [comment] 2021-12-08 21:25
I created a separate issue #224 to collect all optimization notes, until can start refactoring.

**Comment by puzrin** [comment] 2021-12-10 04:41
Released v9 with fixes.

**Closed by puzrin** 2021-12-10 04:41 UTC
Labels: bug
