### ISSUE TITLE
Pica causing a crash in Chrome 64 / Safari 11

### ISSUE THREAD

**Issue by stefanhayden** [nodeca/pica#135] opened 2018-03-16 21:04 UTC
https://jsfiddle.net/uyczfLdk/21/

- open jsfiddle in chrome 64
- click resize button
- wait 2 - 10 seconds
- observe browser tab crash

The above JS fiddle is taking an 800px wide image and resizing it down to 4 pixels. 

This seems to cause Chrome 64 on mac os 10.12.6 (Sierra) to crash with a warning in the Sources tab that there is an out of memory problem. Safari 11 seems to just spin a beach ball. Firefox 58 seems to work fine.

I think it is some what related to the multiple of the resize. I've seen making something 100x smaller work but not when it reaches 150+ smaller.

**Comment by puzrin** [comment] 2018-03-16 22:09
Probably https://github.com/nodeca/pica/issues/124. I have no OSX to debug why [patch](https://github.com/nodeca/multimath/commit/82eaabb7f4d89c64457d300e353ba2fcff62df78) did not helped

**Comment by stefanhayden** [comment] 2018-03-16 23:26
Just confirming now the jsfiddle also has the same behavior on chrome 64 on windows 10.

**Comment by puzrin** [comment] 2018-03-16 23:46
I confirm, example is reproducible in ubuntu & chrome 65.

But in the same time, http://nodeca.github.io/pica/demo/ still works.

**Comment by stefanhayden** [comment] 2018-03-17 00:41
the demo seems to work because it's not resizing the image enough. In my fork if I just change the resize canvas to 3px wide it now crashes on load: https://stefanhayden.github.io/pica/demo/

**Comment by puzrin** [comment] 2018-03-17 01:01
Ok, i've played a bit with your code, seems it crashes below 6x6 px. That's amaizing, but main question is - do any actions really needed (such small sizes seems useless)?

If yes, second question will be - is it a pica bug or webkit bug, does actions needed in this repo or in chrome tracker?

**Comment by stefanhayden** [comment] 2018-03-17 01:04
I don't think it's pixel size.. it's factor of change. 

so if you have a 10000px image and go down to 50px that is is a 200 times smaller and i'm confident that will also crash.

**Comment by puzrin** [comment] 2018-03-17 01:16
I don't understand:

- how can it be a factor of change, if that's browser-specific?
- https://github.com/nodeca/pica/blob/master/test/brightness.js - you can play here with any sizes (downscale), math does not crash.

**Comment by stefanhayden** [comment] 2018-03-17 01:37
- yeah I'm not sure but factor of change seems to be how I was able to reproduce it consistently
- I can get the test to fail on a resize but I don't know if it's the same kind of failure: https://github.com/stefanhayden/pica/commit/b99072abedcfac7e853fa15bdfe4e4e757151231

**Comment by stefanhayden** [comment] 2018-03-17 01:50
On second thought I think it must be the same failure because if I use the same values from the demo page I get the same failure in the mocha test 3264 x 2448 -> 3x3 give some failure comparing some data structure I don't understand.

**Comment by asturur** [comment] 2018-03-17 04:40
It has to be noted that in firefox it does not crash.

I remember seeing in some debug session, outside the scope of the minimal demo, some kind of pica internal for loop, looping while `i < something.width` but incrementing i of some negative values. so basically looping forever.

I have no idea if this can ring some bell

**Comment by puzrin** [comment] 2018-03-17 07:55
@stefanhayden

> I can get the test to fail on a resize but I don't know if it's the same kind of failure: 

That's not related. Raw math does NOT hang, as in your example.

This test checks that enegry does not deviate too much (white will be white after resize, not gray). Input/output are raw RGBA data. Assertion fails, because there are some minor deffects on the edges. But that's not related to your problem anyhow.

Since math is ok, the rest is canvas read/write. I think this can be reproduced without pica at all. And, as i said, existing example is for very small output size, not valuable in real world.

**Comment by puzrin** [comment] 2018-03-17 08:54
If anyone wish to narrow down error place, i'd suggest to take https://github.com/nodeca/pica/blob/master/index.js and do this steps:

- drop resize RGBA call, replace with dummy function, returning 3x3 px result (`new Uint8Array(8)`)
- drop tiler call, image read and so on. Default tile size is 1024x1024. Source is 800x600, so there will be only one resize op.
- only [this](https://github.com/nodeca/pica/blob/17e179003dfd3a78fd990cebda175bb6ff36c00c/index.js#L395-L427) code will be left for fixed 3x3 size (i think so), and it should crash.

**Comment by puzrin** [comment] 2018-03-17 09:16
Hm... https://jsfiddle.net/k0cq8guw/9/ this code does not crash. Need more accurate cleanup of [processTile](https://github.com/nodeca/pica/blob/17e179003dfd3a78fd990cebda175bb6ff36c00c/index.js#L330). But principle is the same as described above.

PS. also worth init pica as `new pica({ features: [ 'js' ] });` - that disable webworkes, webassembly and leave pure js only. Example from first post still crash with such params.

**Comment by asturur** [comment] 2018-03-17 12:14
is not just about 3px.

You can crash reducing an image to 48x48 (an icon size) starting from 12.000px size.

We perfectly understand is an edge case, is still worth to figure out where the error come from and how to fix it.

**Comment by puzrin** [comment] 2018-03-17 17:05
> You can crash reducing an image to 48x48 (an icon size) starting from 12.000px size.

I'd like to see reproducible example.

**Comment by asturur** [comment] 2018-03-17 17:56
monday i ll try again.

**Comment by asturur** [comment] 2018-03-19 17:53
https://jsfiddle.net/uyczfLdk/41/

while my google docs file link is still valid, this fiddle resize to 48x48 and crash.

the starting file is 25+ megs, so please keep the network tab open to see when it finish downloading

**Comment by puzrin** [comment] 2018-03-19 18:02
I can't open image link. Could you create "all white" image of desired dimentions? it should be compact in jpg.

**Comment by asturur** [comment] 2018-03-19 18:13
https://jsfiddle.net/uyczfLdk/42/

Ok this is a white 12k x 12k image.

**Comment by puzrin** [comment] 2018-03-20 18:49
Thank you for help & patience. Seems bug is in tiler logic, when scaledown ratio is > tileSize (1024).

Workaround is to scale down in multiple steps. With min tile size 512, 2 steps will give up to 262144 (512^2) ratio with correct work. That's enougth for any imaginated input. Even iv someone wish to scale down 50000x50000 => 1x1.

Also, to improve speed, first step can be done with more simple filter (lanczos2 instead of lanczos3).

**Comment by puzrin** [comment] 2018-03-20 18:51
BTW, according to investigations, this bug does not depend on browser type. No idea why FF did not crashed, but not principal now.

**Comment by asturur** [comment] 2018-03-20 19:09
I had the gut feeling that was something to do with float rounding of small numbers. But maybe i was wrong.

To us it happens also with scale ratio of 100.
When you talk of scaledown you mean in square area, or linear size?

Can we do something to help fix the bug?

**Comment by puzrin** [comment] 2018-03-20 22:47
> When you talk of scaledown you mean in square area, or linear size?

Any dimention (X or Y). But it's more convenient to use squares in examples.

Big image is splitted by tiles. When we have combination of (1024 / 1..5) ratio, that can freeze. Your previous sample of 12000 -> 48 has it somewhere inside and is "technically the same" as in first post.

> To us it happens also with scale ratio of 100.

If you can provide example with 100, that will help. May be i missed something. Anyway, we will be- fixing not specific values, but whole equations, that should cover all possible ranges at once.

> Can we do something to help fix the bug?

Wait a couple of days. There is at least one obvious bug in tiler's math. We will do a correct fix and will check again if additional actions needed.

**Comment by stefanhayden** [comment] 2018-03-21 01:48
thanks and we look forward to what the fix is!

**Comment by puzrin** [comment] 2018-03-26 23:54
Should be fixed in 4.1.0

**Comment by puzrin** [comment] 2018-03-26 23:55
Ref: https://github.com/nodeca/pica/commit/287296f9a0eb6ff9bde380424cb35381de80d765

**Comment by puzrin** [comment] 2018-03-30 13:14
Let's close this.

**Closed by puzrin** 2018-03-30 13:14 UTC
Labels: bug

**Comment by stefanhayden** [comment] 2018-04-09 13:39
thanks for all the hard work! Update seem to work great!
