### ISSUE TITLE
With Webpack I face below error while using pica

### ISSUE THREAD

**Issue by pradipvaghasiya** [nodeca/pica#76] opened 2017-01-05 06:12 UTC
I am trying to use pica with react app created using create react app module
Anyway to fix this?

`Uncaught TypeError: __webpack_require__(...).readFileSync is not a function
    at Object.<anonymous> (resize_webgl.js:14)
    at Object.<anonymous> (resize_webgl.js:385)
    at __webpack_require__ (bootstrap bb72531…:555)
    at fn (bootstrap bb72531…:86)
    at Object.<anonymous> (index.js:39)
    at __webpack_require__ (bootstrap bb72531…:555)
    at fn (bootstrap bb72531…:86)
    at Object.<anonymous> (App.js:6)
    at __webpack_require__ (bootstrap bb72531…:555)
    at fn (bootstrap bb72531…:86)`

**Comment by puzrin** [comment] 2017-01-05 06:18
Dupe of #73 . You can use file from `dist` folder as alternative

**Closed by puzrin** 2017-01-05 06:18 UTC
