### ISSUE TITLE
Remove need for webpack alias

### ISSUE THREAD

**Issue by redders6600** [nodeca/pica#193] opened 2020-05-11 10:02 UTC
This is related to issue #149 and some others. Basically if you want to use this module with webpack, you need to add a custom resolve alias in your project's webpack configuration.

This is a bit tricky (but not impossible) with a project using `create-react-app` (if you're not from a react world: this is the easiest and fastest way to set up all of the react development boilerplate) without 'ejecting', which has maintainability implications.

I wanted to check if there is a reason that this package doesn't use the `package.json` fields that point webpack in the right direction when resolving modules?

[Webpack docs on this are here](https://webpack.js.org/configuration/resolve/#resolvemainfields) - I would suggest using `browser`?

Happy to make a PR if there's no reason this wouldn't work or shouldn't be done.

**Comment by puzrin** [comment] 2020-05-11 10:06
Reason is still the same - i don't know how to do that WITHOUT breaking development process. Previous suggestions were not acceptable from this point of view. If you know good working solution - let me know.

**Comment by redders6600** [comment] 2020-05-11 11:02
@puzrin there are quite a few issues about this and I can't find the one that explains where/how it breaks the dev process.

Can you let me know how I can test if it breaks it? I think adding a `browser` field to `package.json` should be quite safe.

**Comment by puzrin** [comment] 2020-05-11 12:33
- People suggested to replace `main`.
- What about `browser`
  1. I don't use webpack and don' know if this helps.
  2. Need to check this will not break [browserificaion](https://github.com/nodeca/pica/blob/master/Makefile#L49)

**Comment by puzrin** [comment] 2020-06-09 00:59
Close (dupe of previous, no updates)

**Closed by puzrin** 2020-06-09 00:59 UTC
