### ISSUE TITLE
Resize an image with transparency and other colors

### ISSUE THREAD

**Issue by 2Owy** [nodeca/pica#140] opened 2018-04-25 09:43 UTC
Hy guys !
First I want to thank you all for this great plugin.
I have a little problem and I can not find answers.
When I try to resize a picture with transparency and another color, pica adds a border between transparency and the other color. On white you can see the border really clear on other colors not so much, but is there.

I attached the picture and you can try it on the pica demo page.
Do you have any idea ? Any advices ? Thank you !

![transparencyandnot](https://user-images.githubusercontent.com/19775848/39238093-0dfc0e48-4886-11e8-9558-5fa0f08228d7.png)

**Comment by puzrin** [comment] 2018-04-25 09:46
Dupe of #60. Known bug.

**Closed by puzrin** 2018-04-25 09:46 UTC
