### ISSUE TITLE
Weird issue with Lanczos3 resize. Alpha channel ?

### ISSUE THREAD

**Issue by xan105** [nodeca/pica#123] opened 2017-12-20 04:45 UTC
I'm using this snippet : https://gist.github.com/timdown/021d9c8f2aabc7092df564996f5afbbf to trim the transparent pixel of an image after resizing it.

After a bunch of test i found that when using Lanczos3 resize method there is a small border of transparent pixels left.
But i have 'perfect' trim with all the other methods and with the downscale method used by the browser.
Since the snippet look for alpha 0 pixels could there be something wrong with Lanczos3 ?

I replicated this issue in this demo : [demo.zip](https://github.com/nodeca/pica/files/1574198/demo.zip)

Your insight would be greatly appreciated, thank you.

Firefox 57.0.2 x64
Chrome build 63.0.3239.108 x64

**Comment by puzrin** [comment] 2017-12-20 10:12
Seems dupe of #60

**Comment by puzrin** [comment] 2019-07-26 11:28
Close (as dupe)

**Closed by puzrin** 2019-07-26 11:28 UTC
