### ISSUE TITLE
Magic Kernel support

### ISSUE THREAD

**Issue by vjeux** [nodeca/pica#219] opened 2021-10-11 16:05 UTC
Right now you’re using a standard kernel + blur filter. Would be cool to use the magic kernel in order to get better image quality. See this post for the explanation of how that work: http://www.johncostella.com/magic/

Thanks for all the great work in your lib <3

**Comment by puzrin** [comment] 2021-10-13 19:21
@j-p-c, probably, i could not explain my intents well. There are lot of kernel alternatives (symmetric and non-sypmmetric). I have no experience to create quality estimates, so need some practical criteria:

- suggested feature should be well known & landed wide

I see this:

- provided links are of 2021 (very young)
- not too much results in google
- no technical details about facebook/instagram
- no this kernel in popular image processing libraries

I don't mean this kernel is bad/useless. I just don't see lot of evidences "everybody except you already switched to new kernel".

My personal summary is:

- Currently provided info is not enough. If anybody wish to continue talks about magic kerner - more solid "proofs" required.
- We can drop talks about concrete kernel and discuss api to pass any custom kernel (IMO this could be constructive alternative).
- IMO, if this library is used to "reduce files before upload", computation savings will be not too significant.

**Comment by puzrin** [comment] 2021-10-13 20:29
@j-p-c since diving into "image quality" questions require significant time, i'd like to avoid all kinds of coding & api changes "just for fun".

https://github.com/nodeca/pica/blob/master/lib/mm_resize/resize_filter_info.js - technically, it's not difficult to add one more function. But how to decide where to stop? People can ask to add 10 more kernels. Need criteria how to decide, what to accept/reject. Existing presets are from Skia (chromium) sources.

The most flexible way (not most convenient) - invent `.filter` option to pass any custom kernel, desired by user. Then users will not depend on my opinion, but will have to pass this option "manually", instead of selecting "quality".

With magic kernel, without my personal involvement, alternatives are:

- Find trusted authority (persons). For example, ImageMagic authors created very detailed articles. If they say, "magic kerel is the best" - no problem.
- Find trusted projects. This can be:
  - lot of libraries, accepted this kernel (~ de-facto standard)
  - big websites (like facebook), with detailed reports about kernel params, quality improvements and side effects.

If you have access to info about MK in Facebook, it would be very interesting to read. As i said before, it's not technical problem to add one more preset. Problem is to avoid uncertain things. I have no principal objections against magic kernel, but i can't grade it or spend my own time for investigations.

**Comment by puzrin** [comment] 2021-10-15 15:31
Thank you for details. Very interesting.

Could you comment, why after Facebook used MK(S) 8+ years, this is not landed to other libraries (libvips and others)? https://github.com/libvips/libvips - i guess, authors will be happy to replace [pre-blur + lanczos3] with MKS.

> When Instagram wanted to make use of MKS in 2015, we found that it needed a sharper output (more "pop") to match its existing algorithm. You can get a sharper result by just changing the Sharp filter to {−s, 4 + 2s, −s} / 4 with s > 1, so that the extra sharpening costs no extra cycles. From memory, a value of s of around 1.32 did the job.
> 
> Apart from the extra sharpening, there are no tunable parameters for MKS 2013.

Is extra sharpening useful in real world (for down-sizer), or Instagram case was only for compatibility reason?

---

About pica API

I think, MK(S) does not fit into `.quality` option. So, i think to add `.filter` option:

-  `{ fn: ..., win: ... }` - any custom filter. Internally converted to interpolating Array[100], to safely been passed to webworkers (as simple objects).
- `mks2013` | `box` | `hamming`| `lanczos2` | `lankzos3` (String) - preset name, to simplify use

I suppose, passing `s` as param of MKS will make api too cluttered while "added value" will be not significant. If user wish extra sharpening, existing sharpen options can be used on second call.

**Comment by j-p-c** [comment] 2021-10-15 15:52
Hey Vitaly, I didn't seek to advertise MKS, but provided more information about it on my page (which had the current MK on there since 2011, and an earlier doubling / halving version since 2006) after I figured out theoretically why it all worked so well. It was only this year when I fully figured out it out, hence the research paper. That has gotten more attention. People have made use of MK and MKS over the years, but I have not pushed for its use elsewhere.

My good friend and colleague @vjeux opened this request. He was the person who provided the introduction in 2013 that resulted in me implementing MKS in the first place.

The extra sharpening was primarily for compatibility, but it does provide more "pop" to downsized images, and costs no extra cycles. It definitely can be relegated to a separate filtering, at the expense of cycles.

**Comment by puzrin** [comment] 2021-11-21 21:14
Could you test mks2013 in dev branch https://github.com/nodeca/pica/commits/dev (see last 3 commits)?

Just open `/demo/index.html` in browser.

I see some difference, but sharpening is not significant. Don't know, is that right or not.

**Comment by j-p-c** [comment] 2021-11-21 22:34
I think it is correct. The kernel formula in code looks correct. I have compared a resized image against my reference implementation: there are small differences, but I don't believe you are handling gamma encoding (i.e. you are operating on the gamma-encoded values, rather than converting to linear space), which could explain those differences. I can try to remove the gamma handling of my reference implementation in order to do a direct comparison.

**Comment by j-p-c** [comment] 2021-11-21 23:32
I have added a switch to my reference implementation to turn off the correct handling of gamma encoding. With that switched off, the results are essentially identical to what pica is showing (with all unsharp turned off).

I do notice that, with WebWorker enabled, the diff between the images, when magnified, shows some noticeable vertical and horizontal lines (but not noticeable in the raw image, to the naked eye). These lines disappear when WebWorker is disabled. I assume that there is some sort of batching into rectangles going on with maybe some sort of simplification going on around the edges of those rectangles, rather than correctly using the information in neighboring patches?

In any case, that's a characteristic of pica itself, not related to the implementation of mks2013, which looks to be correct.

**Comment by puzrin** [comment] 2021-11-22 01:16
> I have added a switch to my reference implementation to turn off the correct handling of gamma encoding. With that switched off, the results are essentially identical to what pica is showing (with all unsharp turned off).

Thank you!

In JS there are no access to gamma, and canvas color channels are 8 bits only. That's why readme has note about "pica not recommended for professional quality photos". The only way to improve things is to write jpeg decoder and so on, but this is out of scope.

The only possible to improve thing is keep 16-32 bit precision between vertical and horizontal passes. But i had no time for experiments.

> I do notice that, with WebWorker enabled, the diff between the images, when magnified, shows some noticeable vertical and horizontal lines (but not noticeable in the raw image, to the naked eye). These lines disappear when WebWorker is disabled. I assume that there is some sort of batching into rectangles going on with maybe some sort of simplification going on around the edges of those rectangles, rather than correctly using the information in neighboring patches?

That's strange. When create tiles, pica use extra overlapping borders to avoid edge effects. And generated convolve filters use float offsets (no rounding). There should be no distortion.

The only hack was for safary https://github.com/nodeca/pica/blob/384784f2c27d0eeafabe95604bf1291f1d6e9277/index.js#L354. That should not be related to webworkers.

Try to create new issue, how to reproduce problem and try v6. May be we broken something in v7, when tried to extract data more effectively (to not block main thread).

**Comment by j-p-c** [comment] 2021-11-22 03:21
For gamma, a good default is to assume sRGB, do a lookup to undo gamma encoding to linear space, perform the resizing, and then do another lookup to gamma-encode again. But as you say, with only 8 bits that's not ideal, and to be fair many applications don't resize in linear space anyway. It's reasonable to leave it as-is.

I only came across the patches when looking at the diff (which otherwise was a close match). I'll try to find some time to explore further, and open a new issue. The diff using mks2013 between pica worker and pica non-worker (with mid-gray = 0, differences magnified by a factor of 10) is [shown here](http://johncostella.com/mks2013-worker-minus-non.png). The lines are at x = 107, 108, 209, 210, 319, 320, and y = 103, 104, 209, 210. I don't fully understand those values, but I haven't looked at how the space is divided up in your code. Diffing with the reference implementation image shows that it's the worker one that has the line artifacts (turning that off leaves no lines).

**Comment by puzrin** [comment] 2021-11-22 03:49
Your image shows borders of tiles. This may be browser-specific problem.

AFAIK, pica uses the same tiling process (split source to slightly overlapping areas ~ 1000x1000) both with and without workers. The only difference in v7, it may pass region extraction to worker, but that's not about math.

That's why i suggested you to try v6 for sure. Because in v6 workers do pure math, without browser-specific things (extracting raw bitmaps from images).

**Comment by j-p-c** [comment] 2021-11-22 04:34
Yes, you're right: it is only buggy on Chrome [Version 96.0.4664.55 (Official Build) (x86_64) for Mac] but not on Safari [Version 15.1 (17612.2.9.1.20)] or Firefox [94.0.1 (64-bit)]. I will need to try on v6 as well.

An easy way to check it is with [this test image](http://johncostella.com/pica-chrome-grate.png), which directly shows vertical artifacts on Chrome in WebWorker mode (for all resizing methods), but not otherwise.

(BTW: A different example image showing why MKS2013 is superior to Lanczos is [here](http://johncostella.com/pica-lanczos-grate.png).)

**Comment by j-p-c** [comment] 2021-11-22 04:43
Confirmed: Chrome is also buggy on master but not back on v6.

**Comment by puzrin** [comment] 2021-11-22 06:15
Thank you for your help & test fixtures. As far as i remember, Chrome is currently the only browser with OffscreenCanvas support. That's why other browsers have no such defect.

https://github.com/nodeca/pica/blob/384784f2c27d0eeafabe95604bf1291f1d6e9277/index.js#L272-L284

Removing this code block (may be in `/dist/...`) should disable passing complex objects to Webworker, and force use typed arrays. Disadvantage is blocking main thread while decode images (when draw image region to canvas).

FYI, this is webworker wrapper https://github.com/nodeca/pica/blob/master/lib/worker.js. It normalizes `ImageData` to typed array, if receives. As you can see, no more difference with v6.

In fact, fighting with browser workarounds takes more efforts than implementing math :)

**Comment by puzrin** [comment] 2021-11-22 06:42
Confirming. After commented out block with `OffscreenCanvas` use (passing `ImageData` to WW, instead of typed array), defect in Chrome removed.

Seems browser bug. Need to investigate if workaround possible.

**Comment by puzrin** [comment] 2021-11-22 07:12
https://github.com/nodeca/pica/issues/223

Created separate issue, and found better workaround. We still can use OffscreenCanvas to decode image in WW, but result should stay typed array. Then no defect.

**Comment by j-p-c** [comment] 2021-11-22 14:07
Nice!

> In fact, fighting with browser workarounds takes more efforts than implementing math :)

I had a similar experience with my 2013 implementation with hardware acceleration. Working around the bugs is always tedious!

**Closed** 2021-11-22 18:29 UTC
Labels: enhancement
